# Generated by Django 2.1.1 on 2018-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
